# Generated by Django 2.1.7 on 2019-02-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(default='', max_length=30)),
                ('apellidos', models.CharField(default='', max_length=30)),
                ('nrodocumento', models.CharField(default='', max_length=15, unique=True)),
                ('edad', models.CharField(default='', max_length=3)),
                ('sexo', models.CharField(default='', max_length=70, unique=True)),
                ('nro_contacto', models.CharField(default='', max_length=30)),
                ('nom_contacto', models.CharField(default='', max_length=30)),
                ('fechaIngreso', models.DateTimeField(blank=True, null=True)),
                ('comentarios', models.TextField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
                'ordering': ['fechaIngreso'],
            },
        ),
    ]
