# Generated by Django 2.1.7 on 2019-02-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mba_sys', '0003_auto_20190224_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(blank=True, default=1, null=True)),
                ('descripcion', models.CharField(default='', max_length=70, unique=True)),
                ('fechaInicio', models.DateTimeField(blank=True, null=True)),
                ('fechaFin', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField(default=2019)),
            ],
            options={
                'verbose_name_plural': 'Periodos',
                'ordering': ['numero'],
            },
        ),
    ]
